/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import java.io.*;
import Funciones.AESencripter;
import Funciones.ArchivoSecuencial;
import Funciones.SecuencialIndexado;
import static java.awt.image.ImageObserver.WIDTH;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jaco.mp3.player.MP3Player;
/**
 *
 * @author Roberto Moya
 */
public class Play extends javax.swing.JFrame {

    /**
     * Creates new form Play
     */
    public Play() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBTNMostrar = new javax.swing.JButton();
        JTBNMostrarCancion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTAListas = new javax.swing.JTextArea();
        JTBNVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFCancion = new javax.swing.JTextField();
        JTFLista = new javax.swing.JTextField();
        JBTNReproducir = new javax.swing.JButton();
        JBTNDetener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        JBTNMostrar.setBackground(new java.awt.Color(102, 102, 102));
        JBTNMostrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JBTNMostrar.setForeground(new java.awt.Color(255, 255, 255));
        JBTNMostrar.setText("Mostrar listas");
        JBTNMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNMostrarActionPerformed(evt);
            }
        });

        JTBNMostrarCancion.setBackground(new java.awt.Color(102, 102, 102));
        JTBNMostrarCancion.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTBNMostrarCancion.setForeground(new java.awt.Color(255, 255, 255));
        JTBNMostrarCancion.setText("Mostrar Canciones");
        JTBNMostrarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBNMostrarCancionActionPerformed(evt);
            }
        });

        JTAListas.setBackground(new java.awt.Color(102, 102, 102));
        JTAListas.setColumns(20);
        JTAListas.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTAListas.setForeground(new java.awt.Color(255, 255, 255));
        JTAListas.setRows(5);
        jScrollPane2.setViewportView(JTAListas);

        JTBNVolver.setBackground(new java.awt.Color(102, 102, 102));
        JTBNVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTBNVolver.setForeground(new java.awt.Color(255, 255, 255));
        JTBNVolver.setText("Volver");
        JTBNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBNVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Cancion");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mostrar canciones para esta playlist");

        JTFCancion.setBackground(new java.awt.Color(102, 102, 102));
        JTFCancion.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTFCancion.setForeground(new java.awt.Color(255, 255, 255));
        JTFCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCancionActionPerformed(evt);
            }
        });

        JTFLista.setBackground(new java.awt.Color(102, 102, 102));
        JTFLista.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTFLista.setForeground(new java.awt.Color(255, 255, 255));

        JBTNReproducir.setBackground(new java.awt.Color(102, 102, 102));
        JBTNReproducir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JBTNReproducir.setForeground(new java.awt.Color(255, 255, 255));
        JBTNReproducir.setText("Reproducir");
        JBTNReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNReproducirActionPerformed(evt);
            }
        });

        JBTNDetener.setBackground(new java.awt.Color(102, 102, 102));
        JBTNDetener.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JBTNDetener.setForeground(new java.awt.Color(255, 255, 255));
        JBTNDetener.setText("Detener");
        JBTNDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNDetenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBTNReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JTBNMostrarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(JTFCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(JTFLista, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JBTNMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(JBTNDetener)
                                .addGap(54, 54, 54)
                                .addComponent(JTBNVolver))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(JBTNMostrar)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTBNMostrarCancion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTNReproducir))))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTBNVolver)
                    .addComponent(JBTNDetener))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTNMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNMostrarActionPerformed
        // TODO add your handling code here:
        JTAListas.setText("");
        Login l1= new Login();
        ArchivoSecuencial as = new ArchivoSecuencial();
        ArrayList<String> listaPlaylist = new ArrayList<>();
        listaPlaylist=as.getAll(l1.usertx, "C:\\MEIA\\listas_canciones.txt", "C:\\MEIA\\bitacora_listas_canciones.txt");
        String[] Listas;
        for(int i=0; i<listaPlaylist.size();i++)
        {
            Listas=as.getArreglo(listaPlaylist.get(i));
            if(l1.usertx.equals(Listas[0]))//Imprime solo las playlist de la misma persona
            {
                JTAListas.append(Listas[1]+System.getProperty("line.separator" ));
            }

        }

    }//GEN-LAST:event_JBTNMostrarActionPerformed
public String ObtenerAdmin()
    {
        ArchivoSecuencial as = new ArchivoSecuencial();
        String[][] ArregloLinea=new String[9][2];
        ArregloLinea=as.getDescriptor("C:\\MEIA\\desc_usuario.txt");
        return ArregloLinea[2][1];
    }
    private void JTBNMostrarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBNMostrarCancionActionPerformed
        // TODO add your handling code here:
        JTAListas.setText("");
        String PlaylistForm=JTFLista.getText();
        String DirIndice="C:\\MEIA\\indice.txt",
        DirdescIndice="C:\\MEIA\\desc_indice.txt";
        Login l1= new Login();
        ArchivoSecuencial as = new ArchivoSecuencial();
        SecuencialIndexado si = new SecuencialIndexado();
        String admin=ObtenerAdmin();
        ArrayList<String> listaCancion = new ArrayList<>();
        ArrayList<String> listaLista = new ArrayList<>();
        ArrayList<String> listaPlaylist = new ArrayList<>();
        listaCancion=as.getAll(admin, "C:\\MEIA\\canciones.txt", "C:\\MEIA\\bitacora_canciones.txt");
        listaLista=as.getAll(l1.usertx, "C:\\MEIA\\listas_canciones.txt", "C:\\MEIA\\bitacora_listas_canciones.txt");
        listaPlaylist=si.getAll(l1.usertx, DirIndice, DirdescIndice);
        String[] Canciones;
         String[] Playlist;
         String[] Listas;
         int au=0;
        for(int i=0; i<listaCancion.size();i++)
        {
            Canciones=as.getArreglo(listaCancion.get(i));
            for(int j=0;j<listaPlaylist.size();j++)
            {
                Playlist=as.getArreglo(listaPlaylist.get(j));
               // JTAListas.append(listaPlaylist.get(j)+System.getProperty("line.separator" ));
               for(int h=0;h<listaLista.size();h++)
               {
                   Listas=as.getArreglo(listaLista.get(h));
                   if(Listas[0].equals(Playlist[2]))//User
                   {
                      if(Playlist[3].equals(PlaylistForm))//Playlist
                       {
                          if(Canciones[0].equals(Playlist[4]))//Cancion
                             {
                    
                              JTAListas.append(Canciones[1]+System.getProperty("line.separator" ));
                    
                             } 
                       }
                   }
               }
                

            
            }
            

        }
    }//GEN-LAST:event_JTBNMostrarCancionActionPerformed

    private void JTBNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBNVolverActionPerformed
        // TODO add your handling code here:
        Menu m1 = new Menu();
        m1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JTBNVolverActionPerformed
public String RutaCancion="";
public MP3Player mp3Player;
  public File f ;

    private void JBTNReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNReproducirActionPerformed
        // TODO add your handling code here:
       /* String DirCanciones ="C:\\MEIA\\canciones.txt",
        DirBitCanciones="C:\\MEIA\\bitacora_canciones.txt",
        DirListas ="C:\\MEIA\\listas_canciones.txt",
        DirBitListas="C:\\MEIA\\bitacora_listas_canciones.txt",
        DirIndice="C:\\MEIA\\indice.txt",
        DirdescIndice="C:\\MEIA\\desc_indice.txt";
        Login l1= new Login();
        String Cancion=JTFCancion.getText();
        String Playlist=JTFLista.getText();
        SecuencialIndexado si = new SecuencialIndexado();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime date = LocalDateTime.now();
        String dt = dtf.format(date);
        //Obtener codigo de la cancion
        String codigo="";
        ArchivoSecuencial as = new ArchivoSecuencial();
        
        ArrayList<String> listaCancion = new ArrayList<>();
        ArrayList<String> listaPlaylist = new ArrayList<>();
        ArrayList<String> listaIndice = new ArrayList<>();
        
        listaCancion=as.getAll(l1.usertx, "C:\\MEIA\\canciones.txt", "C:\\MEIA\\bitacora_canciones.txt");
        listaPlaylist=as.getAll(l1.usertx, "C:\\MEIA\\listas_canciones.txt", "C:\\MEIA\\bitacora_listas_canciones.txt");
        String[] Canciones;
        String User=l1.usertx;
        for(int i=0; i<listaCancion.size();i++)
        {
            Canciones=as.getArreglo(listaCancion.get(i));

            if(Canciones[1].equals(Cancion))
            {
                codigo=Canciones[0];
            }

        }

        String informacion=String.join("|",User,Playlist,codigo,User,dt,"1");
        String llave=String.join("|",User,Playlist,codigo);
        //Validaciones para agregar al index
        
        listaIndice = si.getAll(User, DirIndice, DirdescIndice);//ACá
        String[] linea;
        String[] Cn;
        //Los tengo el Arraylists, comienzo a validar
        for(int j=0; j<listaIndice.size();j++)
        {
            linea=as.getArreglo(listaIndice.get(j));
            if(linea[4].equals(codigo))
            {
                if(linea[3].equals(Playlist))
                {
                    for(int l=0;l<listaCancion.size();l++)
                    {
                        Cn=as.getArreglo(listaCancion.get(l));
                        if(Cn[0].equals(codigo))
                        {
                            RutaCancion=Cn[3];
                        }
                    }
                }
            }
            
        }*/
        //****Prueba****
         String DirCanciones ="C:\\MEIA\\canciones.txt",
        DirBitCanciones="C:\\MEIA\\bitacora_canciones.txt";
         Login l1= new Login();
         String Cancion=JTFCancion.getText();
         ArchivoSecuencial as = new ArchivoSecuencial();
         ArrayList<String> listaCancion = new ArrayList<>();
         listaCancion=as.getAll(l1.usertx, "C:\\MEIA\\canciones.txt", "C:\\MEIA\\bitacora_canciones.txt");
         String[] Canciones;
         for(int i=0;i<listaCancion.size();i++)
         {
             Canciones=as.getArreglo(listaCancion.get(i));
             if(Canciones[1].equals(Cancion))
             {
                 RutaCancion=Canciones[3];
             }
         }
         
         
        f=new File(RutaCancion);
        mp3Player =new  MP3Player(f);
        mp3Player.play();
    }//GEN-LAST:event_JBTNReproducirActionPerformed

    private void JBTNDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNDetenerActionPerformed
        // TODO add your handling code here:
        mp3Player.stop();
    }//GEN-LAST:event_JBTNDetenerActionPerformed

    private void JTFCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNDetener;
    private javax.swing.JButton JBTNMostrar;
    private javax.swing.JButton JBTNReproducir;
    private javax.swing.JTextArea JTAListas;
    private javax.swing.JButton JTBNMostrarCancion;
    private javax.swing.JButton JTBNVolver;
    private javax.swing.JTextField JTFCancion;
    private javax.swing.JTextField JTFLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
