/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import Funciones.ArchivoSecuencial;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.awt.Color;
import java.awt.Image;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.ImageIcon;
import Funciones.AESencripter;
import Funciones.ArchivoSecuencial;

public class Playlist extends javax.swing.JFrame {

    /**
     * Creates new form Playlist
     */
    public Playlist() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBTNVolver = new javax.swing.JButton();
        JBTNCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTFPName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        JBTNVolver.setBackground(new java.awt.Color(102, 102, 102));
        JBTNVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JBTNVolver.setForeground(new java.awt.Color(255, 255, 255));
        JBTNVolver.setText("Volver");
        JBTNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNVolverActionPerformed(evt);
            }
        });

        JBTNCrear.setBackground(new java.awt.Color(102, 102, 102));
        JBTNCrear.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JBTNCrear.setForeground(new java.awt.Color(255, 255, 255));
        JBTNCrear.setText("Crear Playlist");
        JBTNCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNCrearActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Playlist");

        JTFPName.setBackground(new java.awt.Color(102, 102, 102));
        JTFPName.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTFPName.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(JTFPName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBTNVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(JBTNCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTNVolver)
                    .addComponent(JBTNCrear))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNVolverActionPerformed
        // TODO add your handling code here:
        Menu m1 = new Menu();
        m1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBTNVolverActionPerformed

    private void JBTNCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNCrearActionPerformed
    
        if(!JTFPName.getText().equals(""))
        {
             Login l1 = new Login();
        String bitacoraUsersPath="C:\\MEIA\\bitacora_listas_canciones.txt"; //Dirección
            String userPath = "C:\\MEIA\\listas_canciones.txt";
            String bitacoraDesc = "C:\\MEIA\\desc_bitacora_listas_canciones.txt";
            String userDec = "C:\\MEIA\\desc_listas_canciones.txt";
           //Valido el codigo
            String[][] fileInfo = new String[9][2];
             String[][] fileInfo2 = new String[9][2];
             String[] LineaLista;
            ArchivoSecuencial list = new ArchivoSecuencial();
            fileInfo= list.getDescriptor(userDec);
            fileInfo2= list.getDescriptor(bitacoraDesc);
            
            int codigo=Integer.parseInt(fileInfo[6][1].trim())+Integer.parseInt(fileInfo2[6][1].trim())+1;
            
            
            //Llenar
            String NombreCancion = JTFPName.getText(),
                    Usuario=l1.usertx;
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDateTime date = LocalDateTime.now();
            String dt = dtf.format(date);
            
            
            String Informacion = String.join("|",Usuario,NombreCancion,Usuario,dt,"1" );
            String strError="";
            String llave=String.join("|",Usuario,NombreCancion);//Nombre playlist, pero no le cambié nombre jeje
            ArchivoSecuencial as = new ArchivoSecuencial();      
           //***********************
            ArrayList<String> listaPlaylist = new ArrayList<>();
            listaPlaylist=as.getAll(l1.usertx, "C:\\MEIA\\listas_canciones.txt", "C:\\MEIA\\bitacora_listas_canciones.txt");
            String[] Listas;
            int h=0;
        for(int i=0; i<listaPlaylist.size();i++)
        {
             Listas=as.getArreglo(listaPlaylist.get(i));
           if(l1.usertx.equals(Listas[0])&&(NombreCancion.equals(Listas[1])))//Imprime solo las playlist de la misma persona
            {
                h=1;
                
                
            }
        }
            //************************
          if(h==0)
          {
               as.Add(Usuario, Informacion, bitacoraUsersPath, userPath, bitacoraDesc, userDec, Usuario, true);     
                Menu m1=new Menu();
                m1.setVisible(true);
                this.dispose();
           }
           else
           {
                JOptionPane.showMessageDialog(null, "La playlist del usuario está repetida");
           }
                
                
           
            
        }
        else
        {
           JOptionPane.showMessageDialog(null, "Escriba el nombre de la playlist"); 
        }
        
    }//GEN-LAST:event_JBTNCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Playlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNCrear;
    private javax.swing.JButton JBTNVolver;
    private javax.swing.JTextField JTFPName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
