/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import java.io.*;
import Funciones.AESencripter;
import Funciones.ArchivoSecuencial;
import Funciones.SecuencialIndexado;
import static java.awt.image.ImageObserver.WIDTH;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



public class SongPlaylist extends javax.swing.JFrame {

    /**
     * Creates new form SongPlaylist
     */
    public SongPlaylist() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBTNMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTAListas = new javax.swing.JTextArea();
        JTBNVolver = new javax.swing.JButton();
        JTBNMostrarCancion = new javax.swing.JButton();
        JTFLista = new javax.swing.JTextField();
        JTFCancion = new javax.swing.JTextField();
        JBTNAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        JBTNMostrar.setBackground(new java.awt.Color(102, 102, 102));
        JBTNMostrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JBTNMostrar.setForeground(new java.awt.Color(255, 255, 255));
        JBTNMostrar.setText("Mostrar listas");
        JBTNMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNMostrarActionPerformed(evt);
            }
        });

        JTAListas.setBackground(new java.awt.Color(102, 102, 102));
        JTAListas.setColumns(20);
        JTAListas.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTAListas.setForeground(new java.awt.Color(255, 255, 255));
        JTAListas.setRows(5);
        jScrollPane2.setViewportView(JTAListas);

        JTBNVolver.setBackground(new java.awt.Color(102, 102, 102));
        JTBNVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTBNVolver.setForeground(new java.awt.Color(255, 255, 255));
        JTBNVolver.setText("Volver");
        JTBNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBNVolverActionPerformed(evt);
            }
        });

        JTBNMostrarCancion.setBackground(new java.awt.Color(102, 102, 102));
        JTBNMostrarCancion.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTBNMostrarCancion.setForeground(new java.awt.Color(255, 255, 255));
        JTBNMostrarCancion.setText("Mostrar Canciones");
        JTBNMostrarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBNMostrarCancionActionPerformed(evt);
            }
        });

        JTFLista.setBackground(new java.awt.Color(102, 102, 102));
        JTFLista.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTFLista.setForeground(new java.awt.Color(255, 255, 255));

        JTFCancion.setBackground(new java.awt.Color(102, 102, 102));
        JTFCancion.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JTFCancion.setForeground(new java.awt.Color(255, 255, 255));

        JBTNAñadir.setBackground(new java.awt.Color(102, 102, 102));
        JBTNAñadir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        JBTNAñadir.setForeground(new java.awt.Color(255, 255, 255));
        JBTNAñadir.setText("Añadir");
        JBTNAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNAñadirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Cancion");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre playlist");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JBTNMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTBNVolver)
                                .addComponent(JTBNMostrarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(JTFCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JTFLista, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(JBTNAñadir)))
                                .addContainerGap(40, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JBTNMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(JTBNMostrarCancion)
                        .addGap(18, 18, 18)
                        .addComponent(JTBNVolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTNAñadir))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //*****************
    
    
    public String ObtenerAdmin()
    {
        ArchivoSecuencial as = new ArchivoSecuencial();
        String[][] ArregloLinea=new String[9][2];
        ArregloLinea=as.getDescriptor("C:\\MEIA\\desc_usuario.txt");
        return ArregloLinea[2][1];
    }
    //***************
    
    private void JBTNMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNMostrarActionPerformed
        // TODO add your handling code here:
        JTAListas.setText("");
        
        Login l1= new Login();
        ArchivoSecuencial as = new ArchivoSecuencial();
        ArrayList<String> listaPlaylist = new ArrayList<>();
        listaPlaylist=as.getAll(l1.usertx, "C:\\MEIA\\listas_canciones.txt", "C:\\MEIA\\bitacora_listas_canciones.txt");
        String[] Listas;
        for(int i=0; i<listaPlaylist.size();i++)
        {
            Listas=as.getArreglo(listaPlaylist.get(i));
            if(l1.usertx.equals(Listas[0]))//Imprime solo las playlist de la misma persona
            {
                JTAListas.append(Listas[1]+System.getProperty("line.separator" ));
            }
            
        }
       
        
    }//GEN-LAST:event_JBTNMostrarActionPerformed

    private void JTBNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBNVolverActionPerformed
        // TODO add your handling code here:
        Menu m1 = new Menu();
        m1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JTBNVolverActionPerformed

    private void JTBNMostrarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBNMostrarCancionActionPerformed
        // TODO add your handling code here:
        JTAListas.setText("");
        String admin=ObtenerAdmin();
        Login l1= new Login();
        ArchivoSecuencial as = new ArchivoSecuencial();
        ArrayList<String> listaCancion = new ArrayList<>();
        listaCancion=as.getAll(admin, "C:\\MEIA\\canciones.txt", "C:\\MEIA\\bitacora_canciones.txt");
        String[] Canciones;
        for(int i=0; i<listaCancion.size();i++)
        {
            Canciones=as.getArreglo(listaCancion.get(i));
            
            JTAListas.append(Canciones[1]+System.getProperty("line.separator" ));
            
            
        }
    }//GEN-LAST:event_JTBNMostrarCancionActionPerformed

    private void JBTNAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNAñadirActionPerformed
        // TODO add your handling code here:
        String DirCanciones ="C:\\MEIA\\canciones.txt",
                DirBitCanciones="C:\\MEIA\\bitacora_canciones.txt",
                DirListas ="C:\\MEIA\\listas_canciones.txt",
                DirBitListas="C:\\MEIA\\bitacora_listas_canciones.txt",
                DirIndice="C:\\MEIA\\indice.txt",
                DirdescIndice="C:\\MEIA\\desc_indice.txt";
        Login l1= new Login();
        String admin=ObtenerAdmin();
        String Cancion=JTFCancion.getText();
        String Playlist=JTFLista.getText();
        SecuencialIndexado si = new SecuencialIndexado();
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDateTime date = LocalDateTime.now();
            String dt = dtf.format(date);
        //Obtener codigo de la cancion
        int codigo=0;
        ArchivoSecuencial as = new ArchivoSecuencial();
        ArrayList<String> listaCancion = new ArrayList<>();
        listaCancion=as.getAll(admin, "C:\\MEIA\\canciones.txt", "C:\\MEIA\\bitacora_canciones.txt");
        String[] Canciones;
        String User=l1.usertx;
         for(int i=0; i<listaCancion.size();i++)
        {
            Canciones=as.getArreglo(listaCancion.get(i));
            
            if(Canciones[1].equals(Cancion))
            {
                codigo=Integer.parseInt(Canciones[0]);
            }
          
        }
        
        String informacion=String.join("|",User,Playlist,codigo+"",User,dt,"1");
        String llave=String.join("|",User,Playlist,codigo+"");
        //Validaciones para agregar al index
         si.Add(llave,informacion,DirIndice, DirdescIndice,User);
        
         
         Menu m1 = new Menu();
        m1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBTNAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SongPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SongPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SongPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SongPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SongPlaylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNAñadir;
    private javax.swing.JButton JBTNMostrar;
    private javax.swing.JTextArea JTAListas;
    private javax.swing.JButton JTBNMostrarCancion;
    private javax.swing.JButton JTBNVolver;
    private javax.swing.JTextField JTFCancion;
    private javax.swing.JTextField JTFLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
